p1project/p1app/urls.py
from django.urls import path

from p1app import views
app_name='p1app'

urlpatterns = [

    path('',views.sample,name='sample'),
    path('movie/<int:movie_id>/',views.detail,name='detail'),
    path('add/',views.add_movie,name='add_movie'),
    path('update/<int:id>/',views.update,name='update'),
    path('delete/<int:id>/',views.delete,name='delete')
]

p1project/p1project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('p1app.urls'))
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

p1project/p1app/models.py
from django.db import models

# Create your models here.
class Movie(models.Model):
    name=models.CharField(max_length=250)
    desc=models.TextField()
    year=models.IntegerField()
    img=models.ImageField(upload_to='gallery')
    price=models.CharField(max_length=250)

    def __str__(self):
        return self.name

p1project/p1app/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect

from .form import MovieForm
from .models import Movie

# Create your views here.
def sample(request):
    movie=Movie.objects.all()
    context={'movie_list':movie}
    return render(request,'index.html',context)

def detail(request,movie_id):
    movie=Movie.objects.get(id=movie_id)
    return render(request,'detail.html',{'movie':movie})
def add_movie(request):
    if request.method=="POST":
        name=request.POST.get('name')
        desc=request.POST.get('desc')
        year=request.POST.get('year')
        img=request.FILES['img']
        movie=Movie(name=name,desc=desc,year=year,img=img)
        movie.save()
        return redirect('/')
    return render(request,'add.html')

def update(request,id):
    movie=Movie.objects.get(id=id)
    form=MovieForm(request.POST or None, request.FILES, instance=movie)
    if form.is_valid():
        form.save()
        return redirect('/')
    return render(request,'edit.html',{'form':form,'movie':movie})

def delete(request,id):
    if request.method=='POST':
        movie=Movie.objects.get(id=id)
        movie.delete()
        return redirect('/')
    return render(request,'delete.html')

p1project/templates/add.html
{% extends 'basse.html' %}
{% block body %}
<form method="POST" enctype="multipart/form-data">
  {% csrf_token %}
  <input type="text" name="name" placeholder="Enter the name"><br><br>
  <input type="text" name="desc"><br><br>
  <input type="number" name="year"><br><br>
  <input type="file" name="img"><br><br>
  <input type="submit" value="SUBMIT">

</form>
{% endblock %}

p1project/templates/basse.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'style.css' %}">
</head>
<body>
<!-- Image and text -->
<nav class="navbar navbar-light bg-success" style="text-align:center;">
  <a class="navbar-brand" href="#" style="text-align:center;>
      <p style="text-align:center;">
      <b>
         Digital Camera
      </b>
      </p>

  </a>
</nav>
{% block body %}
{% endblock %}
</body>
</html>

p1project/templates/delete.html
<form method="POST">
    {% csrf_token %}
    Are you sure to delete..?
    <input type="submit">
</form>

p1project/templates/detail.html
{% extends 'basse.html' %}
{% block body %}
<div class="container">
    <div class="row">
        <div class="col-md-6">
            <img src="{{movie.img.url}}" width="300" height="250">
        </div>

        <div class="col-md-6">
            <h2>{{movie.name}}</h2>
            <h4>{{movie.desc}}</h4>
            <h6>{{movie.year}}</h6>
            <a class="btn btn-warning" href="{% url 'p1app:update' movie.id %}">UPDATE</a>
            <a class="btn btn-danger" href="{% url 'p1app:delete' movie.id %}">DELETE</a>
        </div>

    </div>

</div>
        {% endblock %}

p1project/templates/edit.html
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" value="SUBMIT">



</form>

p1project/templates/index.html
{% extends 'basse.html' %}
<br>
{% block body %}
<br>

<div class="container">
    <div class="row">

{% for i in movie_list %}
        <div class="col-md-3">
            <div class="card">
                  <img class="card-img-top" src="{{i.img.url}}" alt=""  height="200px">

            </div>
            <div class="card-body">
                      <h5 class="card-title">{{i.name}}</h5>
                      <h4 class="card-text"><b>{{i.price}}</b></h4>

                      <a href="{% url 'p1app:detail' i.id %}" class="btn btn-primary">BUY NOW</a>
                      <a href="{% url 'p1app:add_movie' %}" class="btn btn-primary">Add Item</a>
                      <p class="card-text">{{i.desc}}</p>
            </div>

        </div>

        {% endfor %}


    </div>


</div>






{% endblock %}